"""microfix

Revision ID: d20641928ab4
Revises: 7861bbaf9529
Create Date: 2025-05-12 03:27:36.411802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd20641928ab4'
down_revision: Union[str, None] = '7861bbaf9529'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('chat_id', sa.UUID(), nullable=False))
    op.drop_constraint('groups_id_fkey', 'groups', type_='foreignkey')
    op.create_foreign_key(None, 'groups', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.create_foreign_key('groups_id_fkey', 'groups', 'chats', ['id'], ['id'], ondelete='CASCADE')
    op.drop_column('groups', 'chat_id')
    # ### end Alembic commands ###
